// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYDD67uh0HCdbaq2TdQ4X7SpjJNih2BUE',
    appId: '1:822758574252:web:801ec9fe712c46bfe2f709',
    messagingSenderId: '822758574252',
    projectId: 'fishcap-9f4d5',
    authDomain: 'fishcap-9f4d5.firebaseapp.com',
    storageBucket: 'fishcap-9f4d5.firebasestorage.app',
    measurementId: 'G-TJWTTB3MF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCteBVkpik6wQxXF2uvPt3SdL8IrOrDxFo',
    appId: '1:822758574252:android:41eff19f8360c9e1e2f709',
    messagingSenderId: '822758574252',
    projectId: 'fishcap-9f4d5',
    storageBucket: 'fishcap-9f4d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrwV-WeQj4J7-zRNItNZpNgTsY79p7-ZE',
    appId: '1:822758574252:ios:d39506d81d8bdfbfe2f709',
    messagingSenderId: '822758574252',
    projectId: 'fishcap-9f4d5',
    storageBucket: 'fishcap-9f4d5.firebasestorage.app',
    iosBundleId: 'com.example.fishcapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrwV-WeQj4J7-zRNItNZpNgTsY79p7-ZE',
    appId: '1:822758574252:ios:d39506d81d8bdfbfe2f709',
    messagingSenderId: '822758574252',
    projectId: 'fishcap-9f4d5',
    storageBucket: 'fishcap-9f4d5.firebasestorage.app',
    iosBundleId: 'com.example.fishcapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYDD67uh0HCdbaq2TdQ4X7SpjJNih2BUE',
    appId: '1:822758574252:web:4fe4414b2ccf9f1ee2f709',
    messagingSenderId: '822758574252',
    projectId: 'fishcap-9f4d5',
    authDomain: 'fishcap-9f4d5.firebaseapp.com',
    storageBucket: 'fishcap-9f4d5.firebasestorage.app',
    measurementId: 'G-BYQZ0GJLGB',
  );
}
